### ISSUE TITLE
新版SDK

### ISSUE THREAD

**Issue by ReasonYuan** [ybwdaisy/react-native-youzan#10]
有赞官方更新了新版：iOS-SDK 7.1.9 ;  Andoid-SDK 7.1.17
该版本新增的快速授权的新功能。
请问你们什么时候会更新呢？

**Comment by ybwdaisy** [comment]
等测试通过了再更新 SDK

**Comment by ybwdaisy** [comment]
1. iOS react-native-youzan.podspec 没有对 YZAppSDK 版本做限制，直接 pod install --repo-update 升级即可
2. android v1.1.4  版本已经升级至 7.1.17

**Comment by ReasonYuan** [comment]
thanks
