### ISSUE TITLE
无法选择上传本地图片或视频

### ISSUE THREAD

**Issue by ReasonYuan** [ybwdaisy/react-native-youzan#11]
有赞的在线客服页面，可以上传本地图片或视频。
但是在android机上点击页面上的两个按钮，却无反应（iOS未发现该问题）。

可能相关文档：https://doc.youzanyun.com/resource/faq/27034/29160/57401

![1471628511045_ pic](https://user-images.githubusercontent.com/5669911/128703993-535edfae-9b60-412c-8498-41689b35f66e.jpg)

**Comment by ReasonYuan** [comment]
在android机上点击按钮无反应，iOS模拟器上没问题

**Comment by ybwdaisy** [comment]
1. 安卓需要自己实现文件选择逻辑，可以通过onChooser回调触发，并通过实例的静态方法ref.receiveFile回传选择文件路径。￼
2. 后续完善一下文档给出demo。

**Comment by ReasonYuan** [comment]
好的，十分感谢...
