### ISSUE TITLE
ios商品分享，健壮处理

### ISSUE THREAD

**Issue by ReasonYuan** [ybwdaisy/react-native-youzan#9]
商品分享的时候，有些参数可能没有返回，andorid没问题，但iOS会闪退。
例如：[data setObject:[notice.response objectForKey:@"desc"] forKey:@"desc"];
若没有desc字段，会导致iOS闪退。
请对此作健壮处理。

**Comment by ybwdaisy** [comment]
> 商品分享的时候，有些参数可能没有返回，andorid没问题，但iOS会闪退。
> 例如：[data setObject:[notice.response objectForKey:@"desc"] forKey:@"desc"];
> 若没有desc字段，会导致iOS闪退。
> 请对此作健壮处理。

OK

**Comment by ybwdaisy** [comment]
v1.1.4 已处理，升级即可

**Comment by ReasonYuan** [comment]
thanks
